eureka:  
  client:
    serviceUrl:
      defaultZone: http://discovery-service-primary:8001/eureka/,http://discovery-service-secondary:8002/eureka/,http://discovery-service-tertiary:8003/eureka/

spring:  
  profiles: default
          
server:
  port: 11000
