spring:  
  profiles: default

eureka:  
  client:
    serviceUrl:
      #defaultZone: http://discovery-service-primary:8001/eureka/,http://discovery-service-secondary:8002/eureka/,http://discovery-service-tertiary:8003/eureka/
      defaultZone: http://discovery-server:8001/eureka
          
server:
  port: 11000

ribbon:
  eureka:
    enabled: true
---    
spring:  
  profiles: primary

eureka:  
  client:
    serviceUrl:
      defaultZone: http://discovery-service-primary:8001/eureka/,http://discovery-service-secondary:8002/eureka/,http://discovery-service-tertiary:8003/eureka/
          
server:
  port: 11001

ribbon:
  eureka:
    enabled: true
---
spring:  
  profiles: secondary

eureka:  
  client:
    serviceUrl:
      defaultZone: http://discovery-service-primary:8001/eureka/,http://discovery-service-secondary:8002/eureka/,http://discovery-service-tertiary:8003/eureka/
          
server:
  port: 11002

ribbon:
  eureka:
    enabled: true

