spring:
  profiles: default
  application:
    name: discovery-service
server:
  port: 8000  
eureka:
  instance:
    hostname: discoveryhost 
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/    

---
spring:
  application:
    name: discovery-service-clustered   
  profiles: primary
server:
  port: 8001  
eureka:
  instance:
    hostname: discovery-service-primary       
  client:
    registerWithEureka: true
    fetchRegistry: true        
    serviceUrl:
      defaultZone: http://discovery-service-secondary:8002/eureka/,http://discovery-service-tertiary:8003/eureka/

---
spring:
  application:
    name: discovery-service-clustered      
  profiles: secondary
server:
  port: 8002
eureka:
  instance:
    hostname: discovery-service-secondary       
  client:
    registerWithEureka: true
    fetchRegistry: true        
    serviceUrl:
      defaultZone: http://discovery-service-tertiary:8003/eureka/,http://discovery-service-primary:8001/eureka/

---
spring:
  application:
    name: discovery-service-clustered      
  profiles: tertiary
server:
  port: 8003
eureka:
  instance:
    hostname: discovery-service-tertiary       
  client:
    registerWithEureka: true
    fetchRegistry: true    
    serviceUrl:
      defaultZone: http://discovery-service-primary:8001/eureka/,http://discovery-service-secondary:8002/eureka/      