info:
  component: Edge Server
  
endpoints:
  restart:
    enabled: true
  shutdown:
    enabled: true
  health:
    sensitive: false
    
zuul:
  prefix: /api
  routes:
    account-service: 
      path: /account/**
      service-id: account-service
    customer-service:
      path: /customer/**
      service-id: customer-service
      
eureka: 
  client: 
    serviceUrl:
      #defaultZone: http://discoveryhost:8000/eureka/,http://discovery-service-primary:8001/eureka/,http://discovery-service-secondary:8002/eureka/,http://discovery-service-tertiary:8003/eureka/
      defaultZone: http://discovery-server:8001/eureka/
    registerWithEureka: true

server:
  port: 10000
spring:
  profiles: default

ribbon:
  eureka:
    enabled: true

logging:
  level:
    ROOT: INFO
    org.springframework.web: DEBUG
    
  